version: "3.8"

services: 

  db:
    build:
        context: ./database
        dockerfile: Dockerfile
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=400
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_SCHEMA: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    networks:
      - network
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - db

volumes:
  db:
    driver: local
  
# A local docker network.
networks:
  network:
    driver: bridge